# permissions for end users to view redisms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisms-viewer-role
rules:
- apiGroups:
  - cache.mercury200hg.com
  resources:
  - redisms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.mercury200hg.com
  resources:
  - redisms/status
  verbs:
  - get
