
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cache.mercury200hg.com
  resources:
  - redisms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.mercury200hg.com
  resources:
  - redisms/finalizers
  verbs:
  - update
- apiGroups:
  - cache.mercury200hg.com
  resources:
  - redisms/status
  verbs:
  - get
  - patch
  - update
